services:
  db-local-postgres:
    container_name: comments-postgres-local
    image: postgres:16
    environment:
      POSTGRES_USER: mirkamol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comments_db
    ports:
      - "5333:5432"
    restart: unless-stopped
    volumes:
      - db-local:/data/postgres
    networks:
      - mir

networks:
  mir:
    driver: bridge

volumes:
  db-local: