server:
  port: 8080
  servlet:
    context-path: /api/v1
spring:
  application:
    name: comment-to-ticket-triage
  datasource:
    username: mirkamol
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5333/comments_db
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  web:
    error:
      include-message: always
ai:
  huggingface:
    token: ""